# ref: https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml

name: Continuous integration for tools

on:
  push:
    branches: [ main ]
    paths:
      - tools/**
      - .github/workflows/tools_ci.yml
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.9", "3.8", "3.7"]
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pytest-randomly
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 tools --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 tools --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics
    - name: Test with pytest
      run: |
        cd tools/deploy_slide
        pytest -sv
